### ISSUE TITLE
map is used wrong

### ISSUE THREAD

**Issue by Test-subj** [Pakequis/arduino-quake-flicker-lamp#1]
map(value, 0, 26, 0, 255);
should be 
value= map(value, 0, 25, 0, 255);
without value= added there, it doesn't save what it's mapping, and 0,26 is mapping 27 values which leaves z at 245.

**Comment by Pakequis** [comment]
Hello.

Correct, is 0 to 25.

The map() function works without the "value = " and this curious. But I added the "value =" anyway.

Thanks!
